[package]
name = "matrix-protos-rust"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
protobuf = "2.25.1"

[build-dependencies]
protobuf-codegen-pure = "2.25.1"
reqwest = "0.11.4"
zip = "0.5.13"